export const Plant = {
	id: '5faa00621620cb0017da7e35',
	species: 'Arugula',
	images: require('../assets/plant_images/arugula.jpg'),
	description:
		'Arugula is a fast-growing, cool-season salad green that adds a tangy, mustard-like flavor to salads.',
	requirements: [
		'Full Sun',
		'Nutrient-rich Soil',
		'Well-drained Soil',
		'Soil Acidity between 6.0 - 7.0 pH',
	],
	depth: 0.25,
	spacing: 1,
	height: 12,
	width: 12,
	soil_temp_low: 45,
	soil_temp_high: 65,
	days_to_germinate: 7,
	days_to_harvest_short: 40,
	days_to_harvest_long: 60,
	sun: 'Full',
	water: 'Moderate',
	pH: [6, 7],
	nutrient: 'balanced',
	byproducts: [null],
	succession: [14, 21],
	companions: [
		'basil',
		'beans',
		'beets',
		'borage',
		'carrot',
		'celery',
		'chamomile',
		'chives',
		'coriander',
		'corn',
		'cucumber',
		'dill',
		'lettuce',
		'onion',
		'oregano',
		'nasturtium',
		'mint',
		'parsley',
		'petunias',
		'potato',
		'rosemary',
		'sage',
		'spinach',
		'swiss chard',
		'thyme',
	],
	non_companions: [
		'strawberries',
		'eggplant',
		'peppers',
		'potatoes',
		'tomato',
		'cabbage',
	],
	avoid: [
		'Avoid planting where its relatives (other Brassicas) have recently been planted',
	],
	indoorSeed: [
		{
			directions:
				'Prepare a medium container with light potting soil and a hand full of compost',
			image: null,
			requirements: [null],
		},
		{
			directions: 'Place 1 - 2 seeds in container',
			image: null,
			requirements: [null],
		},
		{
			directions: 'Lightly push seed 1/4 inch into soil and cover',
			image: null,
			requirements: [null],
		},
		{
			directions:
				'Lightly water in seeds using the mist setting making sure to saturate seedlings and soil',
			image: null,
			requirements: [null],
		},
	],
	outdoorSeed: [
		{
			directions: 'Locate a planting space',
			image: null,
			requirements: [null],
		},
		{
			directions: 'Prepare beds by digging 6 - 10 inches in well drained soil',
			image: null,
			requirements: [null],
		},
		{
			directions:
				'Add compost and a handful of organic fertilizer for each plant filling back in',
			image: null,
			requirements: [null],
		},
		{
			directions: 'Cover seeds with 1/4 inch of soil',
			image: null,
			requirements: [null],
		},
		{
			directions:
				'Lightly water in seeds using the mist setting making sure to saturate seedlings and surrounding soil',
			image: null,
			requirements: [null],
		},
	],
	starter: [
		{
			directions: 'Locate a planting space',
			image: null,
			requirements: [null],
		},
		{
			directions: 'Prepare beds by digging 6 - 10 inches in well drained soil',
			image: null,
			requirements: [null],
		},
		{
			directions:
				'Add compost and a handful of organic fertilizer for each plant filling back in',
			image: null,
			requirements: [null],
		},

		{
			directions:
				'Lightly water in seeds using the mist setting making sure to saturate seedlings and surrounding soil',
			image: null,
			requirements: [null],
		},
	],
	zone: {
		_1a: [null],
		_1b: [null],
		_2a: [null],
		_2b: [null],
		_3a: ['Apr', 'May', 'Jun'],
		_3b: ['Apr', 'May', 'Jun'],
		_4a: ['Apr', 'May', 'Jun'],
		_4b: ['Apr', 'May', 'Jun'],
		_5a: ['Apr', 'May', 'Jun'],
		_5b: ['Apr', 'May', 'Jun'],
		_6a: ['Apr', 'May', 'Aug'],
		_6b: ['Apr', 'May', 'Aug'],
		_7a: ['Mar', 'Apr', 'Aug', 'Sep'],
		_7b: ['Mar', 'Apr', 'Aug', 'Sep'],
		_8a: ['Feb', 'Mar', 'Sep', 'Oct'],
		_8b: ['Feb', 'Mar', 'Sep', 'Oct'],
		_9a: ['Feb', 'Mar', 'Sep', 'Oct'],
		_9b: ['Feb', 'Mar', 'Sep', 'Oct'],
		_10a: ['Feb', 'Mar', 'Sep', 'Oct'],
		_10b: ['Feb', 'Mar', 'Sep', 'Oct'],
		_11a: ['Feb', 'Mar', 'Sep', 'Oct'],
		_11b: ['Feb', 'Mar', 'Sep', 'Oct'],
		_12a: [null],
		_12b: [null],
		_13a: [null],
		_13b: [null],
	},
}
